name: plutter
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.0
  image_picker:
  file_picker:
  material_design_icons_flutter:
  camera: ^0.5.8+11
  provider: ^4.3.2+2
  firebase_core: ^0.5.2+1
  cloud_firestore: ^0.14.3
  firebase_storage: ^5.0.1
  firebase_analytics: "^6.2.0"
  firebase_auth: ^0.18.3+1


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

 
  uses-material-design: true


  assets:
      
    - assets/images/profile.png
    - assets/images/plutterSplash.jpeg


  fonts:
    - family: Satisfy
      fonts:
        - asset: assets/fonts/Satisfy.ttf
